---

- name: Install kuechenradio
  pip:
    name: Mopidy-HTTP-Kuechenradio
    state: "{{ 'present' if mopidy_raspbian_install_kuechenradio else 'absent' }}"
  notify: restart mopidy

- name: Enable mopify
  ini_file:
    dest: "{{ mopidy_conf_path }}"
    section: 'http-kuechenradio'
    option: enabled
    value: "{{ 'true' if mopidy_raspbian_install_kuechenradio else 'false' }}"
    backup: yes
  notify: restart mopidy
