---

- name: Pip mopify
  pip:
    name: Mopidy-Mopify
    state: "{{ 'present' if mopidy_raspbian_install_mopify else 'absent' }}"
  notify: restart mopidy

- name: Disable mopify
  ini_file:
    dest: "{{ mopidy_conf_path }}"
    section: mopify
    option: enabled
    value: "{{ 'true' if mopidy_raspbian_install_mopify else 'false' }}"
    backup: yes
  notify: restart mopidy
