---

- name: Apt mopidy-spotify extension
  apt:
    name: mopidy-spotify
    state: "{{ 'latest' if mopidy_raspbian_enable_spotify else 'absent' }}"
  notify: restart mopidy

- name: Spotify config
  ini_file:
    dest: "{{ mopidy_conf_path }}"
    section: spotify
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - { option: enabled  , value: "{{ 'true' if mopidy_raspbian_enable_spotify else 'false' }}" }
    - { option: username , value: "{{ mopidy_raspbian_spotify_username }}" }
    - { option: password , value: "{{ mopidy_raspbian_spotify_password }}" }
  notify: restart mopidy
